### ISSUE TITLE
Use CAS without LDAP

### ISSUE THREAD

**Issue by enboig** [ColdTrick/simplesaml#13]
Is it possible to configure CAS without a LDAP server? I have a working CAS server using drupal

I have tried but I cannot find the options.

**Comment by jdalsem** [comment]
LDAP is not required for CAS. With this plugin you should be able to connect to CAS servers (as Service Provider). What problems do you have setting up this plugin?

**Comment by enboig** [comment]
My problem was configuring simplesamlphp
In file simplesamlphp/modules/cas/lib/Auth/Source/CAS.php there is:

    if (!array_key_exists('ldap', $config)){
      throw new Exception('ldap authentication source is not properly configured: missing [ldap]');
    }
    $this->_ldapConfig = $config['ldap'];

I commented all the ldap lines and now no exception is throught.

My problem now is that after redireting my user to my cas server with url

https://login.escoltesiguies.cat/?service=http%3A%2F%2Fsocial.escoltesiguies.cat%2Fsimplesaml%2Fmodule.php%2Fcas%2Flinkback.php%3FstateID%3D_0bb5b57ee40548d98a7ced85df3487047f570135a6%253Ahttp%253A%252F%252Fsocial.escoltesiguies.cat%252Fsimplesaml%252Fmodule.php%252Fcore%252Fas_login.php%253FAuthId%253Dlogin.escoltesiguies.cat%2526ReturnTo%253Dhttp%25253A%25252F%25252Fsocial.escoltesiguies.cat%25252Fsaml%25252Flogin%25252Flogin.escoltesiguies.cat

User don't come back to elgg.
My authsources.php i simplesamlphp is
        $config = array(
            'admin' => array(
                'core:AdminPassword',
            ),
            'login.escoltesiguies.cat' => array(
                'cas:CAS',
                'cas' => array(
                    'login' => 'https://login.escoltesiguies.cat/',
                    'validate' => 'https://login.escoltesiguies.cat/',
                    'logout' => 'https://login.escoltesiguies.cat/logout'
                ),
            ),
        );

My CAS server work (tested with a glpi installation), but there I just had to configure one url (https://login.escoltesiguies.cat/cas) and linked attributes.

I think my problem is with simplesamlphp but I am a little lost here. Could you help me?

thanks.

**Comment by jdalsem** [comment]
I also think that the solution should be somewhere in simplesamlphp, so maybe you could look for support on https://simplesamlphp.org
