### ISSUE TITLE
Are the SimpleSAMLPHP hacks needed or not?

### ISSUE THREAD

**Issue by juho-jaakkola** [ColdTrick/simplesaml#16]
According to the commit 3ab64dfa821ad64393a4e6c4d7da7f517f84aabf it is not necessary to hack the SimpleSAMLPHP library anymore. I'm however not able to make the system work without the hacks.

How can e.g. this work unless the Elgg core is loaded: https://github.com/ColdTrick/simplesaml/blob/master/vendors/simplesamlphp/modules/authelgg/lib/Auth/Source/External.php#L61 ?

Am I missing something or has there been some confusion when updating INSTALL.txt?

**Comment by jeabakker** [comment]
did you re-do the step 5 https://github.com/ColdTrick/simplesaml/blob/master/INSTALL.txt#L23-L28

the reason the hack was needed was because of a session storage conflict. If you set SimpleSAMLPHP to a different storage than all should be fine

**Comment by juho-jaakkola** [comment]
Yes, I've done step 5.

I don't understand how can the `elgg_is_logged_in()` work if Elgg core is not loaded anymore: https://github.com/ColdTrick/simplesaml/commit/3ab64dfa821ad64393a4e6c4d7da7f517f84aabf#diff-48d1bc6644af8a5b129735ddf46363c4L24

**Comment by jeabakker** [comment]
there is no `elgg_is_logged_in()` in SimpleSAMLPHP so what do you mean?

**Comment by juho-jaakkola** [comment]
The plugin that gets installed to it has it: https://github.com/ColdTrick/simplesaml/blob/master/INSTALL.txt#L94

**Comment by jeabakker** [comment]
ahhhh, that plugin hasn't been updated (yet). 

Maybe that plugin should include the core, we don't have many sites that provide IDP functionality, so that slipped by

**Comment by jeabakker** [comment]
ps: haven't tested my change in documentation
