### ISSUE TITLE
Confusing wording on the plugin configuration page

### ISSUE THREAD

**Issue by sdrozdet** [ColdTrick/simplesaml#19]
The plugin setting page had us stumped for a bit. The first text box has the following help text, "The full path to the SimpleSAMLPHP (http://simplesamlphp.org) library without a trailing slash (/)". We initially though it was asking for the full URL, like https://ourserver.com/simplesamlphp.

Instead, it's asking for the location of the library on the server.

Proposal:

Server path to the SimpleSAMLPHP library:
[text box]
_Path to the installed library without the trailing slash (for example, /var/lib/simplesamlphp)_

The link to http://simplesamlphp.org can be moved to the introductory part of the page, or just left in the instructions.

(Besides that, thanks for a sweet plugin!)

**Comment by jdalsem** [comment]
Not going to fix this. This plugin is no longer maintained.
