### ISSUE TITLE
Server error log

### ISSUE THREAD

**Issue by dragonjon** [ColdTrick/simplesaml#20]
Hi, configuring your Elgg module and testing in Elgg 2.1.2 and SimplesamlPHP 1.14.11
In the login page I select de IDP login -> go to IDP select ->login in IDP selected -> return me to IDP select again, no to Elgg.
```
NOTICE: PHP (errno 8): 2017-05-09 12:48:06 (CEST): "Undefined index: REFERER" in file /elggsp/public_html/mod/simplesaml/pages/login.php (line 47), referer: http://ellgsp/login
NOTICE: PHP (errno 8): 2017-05-09 12:48:21 (CEST): "Undefined index: REFERER" in file /elggsp/public_html/mod/simplesaml/pages/login.php (line 47), referer: http://myidp/simplesaml/module.php/core/loginuserpass.php?
```
Note: I change the real URL
I test in the simplesaml Test authentication sources in Elgg SP side and the login in IDP is correct an return me the attributes.
My IDP is working with other SP system (worpress) correctly
Thanks in advanced.
Jon

**Comment by jeabakker** [comment]
for some reason `$_SERVER['REFERER']` is empty. this can happen if you entered the url directly and not were forwarded (by your browser) to the page.

Maybe some PHP setting preventing this from getting filled?

**Comment by dragonjon** [comment]
Hi Jerôme, thanks for the fast response and sorry for not answering before, I had to check everything.
I have reviewed the global settings of php and they were fine, also check the simpleamlphp for if in some file configuring there was something strange but without success.
Finally I thought to clean the database used for the session by your module and started working correctly.

One last question in relation to your module.
Is it possible to add more attributes from the ISP and link them with fields created with the Profile Manager module? Is easy?
And I also have some field like Role generated by other module that I would like to link with the role of ISP

Thanks in advance and good work
Jon

**Comment by jeabakker** [comment]
> One last question in relation to your module.
> Is it possible to add more attributes from the ISP and link them with fields created with the Profile Manager module? Is easy?

In the configuration of the link you can set it to store all the IDP data. You can verify this (as an admin) on the user's plugin settings page.
This saved data can then be read by another plugin to do what you want.

So it can be done, if it's easy depends on your coding skills ;)

**Comment by dragonjon** [comment]
Hi Jerôme
"In the configuration of the link you can set it to store all the IDP data. You can verify this (as an admin) on the user's plugin settings page."
I have seen this and it is correct. But I imagine that for those attributes to be used in other modules have to change the code in those modules. Is correct?
My coding skills are limited, could you help me with the code?

**Comment by jeabakker** [comment]
> But I imagine that for those attributes to be used in other modules have to change the code in those modules. Is correct?

correct

> My coding skills are limited, could you help me with the code?

I don't have an example code available. If you really need our help you can ask for a quote on info@coldtrick.com

**Comment by dragonjon** [comment]
Ok Jerôme, today I write to you and I tell you that I need.

Thanks
Jon

**Comment by dragonjon** [comment]
Hi Jerôme, I wrote you a few days ago to the email you indicated. Did you get it?

Thanks
Jon

**Comment by jeabakker** [comment]
> Hi Jerôme, I wrote you a few days ago to the email you indicated. Did you get it?

yes i got it, will respond soon(tm)
